#!/bin/sh
# creates png images from tga
# plays nice with dom3 shadows
#
#  1. install GraphicsMagick
#  2. place this script in image folder
#  3. execute script
#
gm mogrify -size 128x128 -format png \
	-transparent "#000000" \
	-bordercolor none -border 1x1 -trim \
	-fuzz "4%%" -fill "#000000AA" -opaque "#ff00ff" \
	-geometry "128x128>" \
	*.tga
